config/routes.rb
Rails.application.routes.draw do
 resources :books
 root :to => redirect('/books')
 
 resources :books do
  get 'show_same', :on => :member
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    # add to app/models/Books.rb
    def self.all_generes; 
        ['Science fiction', 'Drama', 'Action and adventure', 'Romance', 'Mystery', 'Horror']; 
    end #  shortcut: array of strings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        if !params.key?(:books)
          params[:books] = {}
        end
        generesss = params[:generes] ? params[:generes].keys : []
        permitted = params.permit(:sort, :generes => generesss)
        sort = params[:sort] || session[:sort]
        case sort
            when 'title'
              ordering,@title_header = {:title => :asc}, 'hilite'
            when 'publish_date'      
              ordering,@date_header = {:publish_date => :asc}, 'hilite'
        end
        
        # edit the index method of the movies_controller.rb
        @all_generes = Book.all_generes  
        @selected_generes = permitted[:generes] || session[:generes] || {}
        if @selected_generes == {}  
          @selected_generes = Hash[@all_generes.map {|genere| [genere, genere]}]
        end
        
        if permitted[:sort] != session[:sort] or permitted[:generes] != session[:generes]
          session[:sort] = sort
          session[:generes] = @selected_generes
         redirect_to :sort => sort, :generes => @selected_generes and return
        end
        
        # @books = Book.all
        # @books = Book.order(ordering)
        @books = Book.where(genere: @selected_generes.keys).order(ordering)
    end
    
    def show
        id = params[:id] # retrieve book title from URI route
        @book = Book.find(id) # look up book by unique ID
        # will render app/views/books/show.html.haml by default
    end
    
    def new
        @book = Book.new
    end
    
    def create
      params.require(:book)
      permitted = params[:book].permit(:title, :genere, :description, :isbn_number, :publish_date, :author)
      @book = Book.create!(permitted)
      flash[:notice] = "#{@book.title} was successfully created."
      redirect_to books_path
    end
    
    def edit
        @book = Book.find params[:id]
    end
    
    def update
        @book = Book.find params[:id]
        params.require(:book)
        permitted = params[:book].permit(:title, :genere, :description, :isbn_number, :release_date, :author)
        @book.update_attributes!(permitted)
        flash[:notice] = "#{@book.title} was successfully updated."
        redirect_to book_path(@book)
    end
    
    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      flash[:notice] = "Book '#{@book.title}' deleted."
      redirect_to books_path
    end
    
    def show_same
      @book = Book.find(params[:id])
      @books_except_self = Book.where.not(title: @book.title)
      @same_author_books = @books_except_self.where(author: @book.author)
      if @same_author_books.empty? then 
        redirect_to books_path 
        flash[:notice] = "'#{@book.title}' has no author info"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.haml
%h2 Edit Book
= form_tag book_path(@book), :method => :put do
    = label :book, :title, 'Title'
    = text_field :book, :title
    = label :book, :genere, 'genere'
    = select :book, :genere, ['Science fiction', 'Drama', 'Action and adventure', 'Romance', 'Mystery', 'Horror']
    = label :book, :description, 'Description'
    = text_field :book, :description
    = label :book, :isbn_number, 'ISBN Number'
    = text_field :book, :isbn_number
    = label :book, :publish_date, 'Publish date'
    = date_select :book, :publish_date
    = label :book, :title, 'Author'
    = text_field :book, :author
    = submit_tag 'Update Book Info'

app/views/books/index.html.haml
-#  This file is app/views/books/index.html.haml
%h1 All Books

-# after the H1 tag
= form_tag books_path, :method => :get, :id => 'generes_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":publish_date_sort", true if @date_header
  Include:
  - @all_generes.each do |genere|
    = genere
    = check_box_tag "generes[#{genere}]", 1, @selected_generes.include?(genere), :id => "generes_#{genere}"
  = submit_tag 'Refresh', :id => 'generes_submit'

%table#books
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Book Title', books_path(:sort => 'title', :generes => @selected_generes), :id => 'title_header'
      %th Genre
      %th Author
      %th Description
      %th{:class => @date_header}= link_to 'Publish Date', books_path(:sort => 'publish_date', :generes => @selected_generes), :id => 'publish_date_header'
      %th ISBN Number
      %th More Info
      
  %tbody
    - @books.each do |book| 
      %tr
        %td= book.title
        %td= book.genere
        %td= book.author
        %td= book.description
        %td= book.publish_date
        %td= book.isbn_number
        %td= link_to "More Info", book_path(book)

-# add to end of index.html.haml
= link_to 'Add new book', new_book_path

app/views/books/new.html.haml
-# create the file app/views/books/new.html.haml
%h2 Create New Book
= form_tag books_path, :method => :post do
 = label :book, :title, 'Title'
 = text_field :book, :title
 = label :book, :genere, 'Genere'
 = select :book, :genere, ['Science fiction', 'Drama', 'Action and adventure', 'Romance', 'Mystery', 'Horror']
 = label :book, :description, 'Description'
 = text_field :book, :description
 = label :book, :isbn_number, 'ISBN Number'
 = text_field :book, :isbn_number
 = label :book, :publish_date, 'Publish date'
 = date_select :book, :publish_date
 = label :book, :author, 'Author'
 = text_field :book, :author
 = submit_tag 'Save Changes'

app/views/books/show.html.haml
-# in app/views/books/show.html.haml
%h2 Details about #{@book.title}
 
%ul#details
  %li
    Genere:
    = @book.genere
  %li
    Author:
    = @book.author
  %li
    ISBN:
    = @book.isbn_number
  %li
    Published:
    = @book.publish_date.strftime("%B %d, %Y")
 
%h3 Description:
 
%p#description= @book.description

= link_to 'Edit book', edit_book_path(@book)
%br
= link_to 'Delete book', book_path(@book), :method => :delete
%br
= link_to 'Go back to listing', books_path
%br
= link_to 'Find Books With Same Author', show_same_book_path(@book.id)

app/views/books/show_same.html.haml
%table#same_author_books
  %thead
    %tr
      %th Book Title
      %th Genre
      %th Author
      %th Description
      %th Publish Date
      %th ISBN Number
      
  %tbody
    - @same_author_books.each do |book| 
      %tr
        %td= book.title
        %td= book.genere
        %td= book.author
        %td= book.description
        %td= book.publish_date
        %td= book.isbn_number

app/views/layouts/application.html.haml
%html
  %head
    %title MyFavouriteBooks!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
 
  %body
    #main
      = yield

-# this goes just inside %body:
- if flash[:notice]
  #notice.message= flash[:notice]
- elsif flash[:warning]
  #warning.message= flash[:warning]